/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.*;
/**
 *
 * @author fohhy
 */
public class CreateVitalJPanel extends javax.swing.JPanel {

    private VitalSignHistory vsh;
    
    /**
     * Creates new form CreateVitalJPanel
     * @param vsh
     */
    public CreateVitalJPanel(VitalSignHistory vsh) {
        initComponents();
        this.vsh = vsh;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        temperatureLabel = new javax.swing.JLabel();
        bloodPressureLabel = new javax.swing.JLabel();
        pluseLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        temperatureText = new javax.swing.JTextField();
        bloodPressureText = new javax.swing.JTextField();
        pluseText = new javax.swing.JTextField();
        dateText = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        headerLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        headerLabel.setText("Create Vital Sign");

        temperatureLabel.setText("temperature");

        bloodPressureLabel.setText("blood pressure");

        pluseLabel.setText("pluse");

        dateLabel.setText("date");

        temperatureText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureTextActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bloodPressureLabel)
                            .addComponent(temperatureLabel)
                            .addComponent(pluseLabel)
                            .addComponent(dateLabel))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(temperatureText)
                            .addComponent(bloodPressureText)
                            .addComponent(pluseText)
                            .addComponent(dateText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(btnSave)))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(headerLabel)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temperatureLabel)
                    .addComponent(temperatureText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodPressureLabel)
                    .addComponent(bloodPressureText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pluseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pluseLabel))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel))
                .addGap(52, 52, 52)
                .addComponent(btnSave)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void temperatureTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperatureTextActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // get data
        double temperature = Double.parseDouble(temperatureText.getText());
        double bloodPressure = Double.parseDouble(bloodPressureText.getText());
        int pluse = Integer.parseInt(pluseText.getText());
        String date = dateText.getText();
        
        //create new obj
        VitalSign vs = vsh.addVital();
        vs.setTemperature(temperature);
        vs.setBloodPressure(bloodPressure);
        vs.setPluse(pluse);
        vs.setDate(date);
        
        // alert msg and clean text box
        javax.swing.JOptionPane.showMessageDialog(null, date + " data saved successfully");
        
        bloodPressureText.setText("");
        temperatureText.setText("");
        pluseText.setText("");
        dateText.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodPressureLabel;
    private javax.swing.JTextField bloodPressureText;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateText;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel pluseLabel;
    private javax.swing.JTextField pluseText;
    private javax.swing.JLabel temperatureLabel;
    private javax.swing.JTextField temperatureText;
    // End of variables declaration//GEN-END:variables
}
